python3 << 'SCRIPT'
code = open("/mnt/user-data/outputs/7zap_inbox/main.py").read() if False else None

lines = [
"from fastapi import FastAPI, HTTPException, Header, Depends, BackgroundTasks",
"from fastapi.middleware.cors import CORSMiddleware",
"from pydantic import BaseModel",
"from typing import Optional",
"from supabase import create_client, Client",
"import httpx, os",
"from datetime import datetime",
"",
"app = FastAPI(title='7zap Inbox API', version='1.0.0')",
"app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])",
"",
"SUPABASE_URL      = os.getenv('SUPABASE_URL')",
"SUPABASE_KEY      = os.getenv('SUPABASE_SERVICE_KEY')",
"WAHA_URL          = os.getenv('WAHA_URL', 'http://localhost:3000')",
"WAHA_KEY          = os.getenv('WAHA_KEY', 'pulsekey')",
"INBOX_API_KEY     = os.getenv('INBOX_API_KEY', '7zap_inbox_secret')",
"ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')",
"",
"supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)",
"",
"def verify_key(x_api_key: str = Header(...)):",
"    if x_api_key != INBOX_API_KEY:",
"        raise HTTPException(status_code=401, detail='Unauthorized')",
"",
"async def waha_send(session, chat_id, text):",
"    async with httpx.AsyncClient(timeout=15) as client:",
"        await client.post(f'{WAHA_URL}/api/sendText', headers={'X-Api-Key': WAHA_KEY}, json={'session': session, 'chatId': chat_id, 'text': text})",
"",
"class SendMessage(BaseModel):",
"    conversation_id: str",
"    text: str",
"    sent_by: Optional[str] = None",
"",
"class AssignConversation(BaseModel):",
"    user_id: Optional[str] = None",
"",
"class UpdateKanban(BaseModel):",
"    stage: str",
"",
"class CreateTask(BaseModel):",
"    title: str",
"    assigned_to: Optional[str] = None",
"    due_at: Optional[str] = None",
"",
"@app.get('/health')",
"async def health():",
"    return {'status': 'ok', 'service': '7zap-inbox'}",
"",
"@app.post('/webhook/inbox')",
"async def webhook_inbox(payload: dict, background_tasks: BackgroundTasks):",
"    if payload.get('event') in ('message', 'message.any'):",
"        background_tasks.add_task(process_message, payload)",
"    return {'received': True}",
"",
"async def process_message(payload: dict):",
"    try:",
"        session = payload.get('session', 'default')",
"        msg = payload.get('payload', {})",
"        if msg.get('fromMe'): return",
"        phone = msg.get('from', '').replace('@c.us', '').replace('@lid', '')",
"        push_name = msg.get('pushName', '') or phone",
"        body = msg.get('body', '')",
"        waha_msg_id = msg.get('id', {}).get('_serialized', '') if isinstance(msg.get('id'), dict) else str(msg.get('id', ''))",
"        if not phone or not body: return",
"        tenant_res = supabase.table('tenants').select('*').eq('waha_session', session).single().execute()",
"        if not tenant_res.data: return",
"        tenant_id = tenant_res.data['id']",
"        contact_res = supabase.table('contacts').upsert({'tenant_id': tenant_id, 'phone': phone, 'push_name': push_name, 'name': push_name, 'updated_at': datetime.utcnow().isoformat()}, on_conflict='tenant_id,phone').execute()",
"        contact_id = contact_res.data[0]['id']",
"        conv_res = supabase.table('conversations').select('*').eq('tenant_id', tenant_id).eq('contact_id', contact_id).in_('status', ['open', 'pending']).order('created_at', desc=True).limit(1).execute()",
"        if conv_res.data:",
"            conv_id = conv_res.data[0]['id']",
"            supabase.table('conversations').update({'last_message_at': datetime.utcnow().isoformat(), 'unread_count': conv_res.data[0]['unread_count'] + 1}).eq('id', conv_id).execute()",
"        else:",
"            conv_id = supabase.table('conversations').insert({'tenant_id': tenant_id, 'contact_id': contact_id, 'status': 'open', 'kanban_stage': 'new', 'last_message_at': datetime.utcnow().isoformat(), 'unread_count': 1}).execute().data[0]['id']",
"        if not supabase.table('messages').select('id').eq('waha_message_id', waha_msg_id).execute().data:",
"            supabase.table('messages').insert({'conversation_id': conv_id, 'tenant_id': tenant_id, 'waha_message_id': waha_msg_id, 'direction': 'inbound', 'content': body, 'type': 'chat'}).execute()",
"        print(f'[INBOX] OK phone={phone} msg={body[:50]}')",
"    except Exception as e:",
"        print(f'[INBOX] ERRO: {e}')",
"",
"@app.get('/conversations', dependencies=[Depends(verify_key)])",
"async def list_conversations(tenant_id: str, status: Optional[str] = None):",
"    q = supabase.table('conversations').select('*, contacts(name, phone, push_name)').eq('tenant_id', tenant_id).order('last_message_at', desc=True)",
"    if status: q = q.eq('status', status)",
"    return {'conversations': q.execute().data}",
"",
"@app.get('/conversations/{conv_id}/messages', dependencies=[Depends(verify_key)])",
"async def get_messages(conv_id: str):",
"    supabase.table('conversations').update({'unread_count': 0}).eq('id', conv_id).execute()",
"    return {'messages': supabase.table('messages').select('*').eq('conversation_id', conv_id).order('created_at').execute().data}",
"",
"@app.post('/conversations/{conv_id}/messages', dependencies=[Depends(verify_key)])",
"async def send_message(conv_id: str, body: SendMessage):",
"    conv = supabase.table('conversations').select('*, contacts(phone), tenants(waha_session)').eq('id', conv_id).single().execute().data",
"    await waha_send(conv['tenants']['waha_session'], conv['contacts']['phone'] + '@c.us', body.text)",
"    res = supabase.table('messages').insert({'conversation_id': conv_id, 'tenant_id': conv['tenant_id'], 'direction': 'outbound', 'content': body.text, 'type': 'chat', 'sent_by': body.sent_by}).execute()",
"    supabase.table('conversations').update({'last_message_at': datetime.utcnow().isoformat()}).eq('id', conv_id).execute()",
"    return res.data[0]",
"",
"@app.put('/conversations/{conv_id}/assign', dependencies=[Depends(verify_key)])",
"async def assign_conversation(conv_id: str, body: AssignConversation):",
"    return supabase.table('conversations').update({'assigned_to': body.user_id}).eq('id', conv_id).execute().data[0]",
"",
"@app.put('/conversations/{conv_id}/kanban', dependencies=[Depends(verify_key)])",
"async def update_kanban(conv_id: str, body: UpdateKanban):",
"    return supabase.table('conversations').update({'kanban_stage': body.stage}).eq('id', conv_id).execute().data[0]",
"",
"@app.put('/conversations/{conv_id}/resolve', dependencies=[Depends(verify_key)])",
"async def resolve_conversation(conv_id: str):",
"    return supabase.table('conversations').update({'status': 'resolved', 'kanban_stage': 'resolved'}).eq('id', conv_id).execute().data[0]",
"",
"@app.get('/tasks', dependencies=[Depends(verify_key)])",
"async def list_tasks(tenant_id: str):",
"    return {'tasks': supabase.table('tasks').select('*').eq('tenant_id', tenant_id).eq('done', False).execute().data}",
"",
"@app.post('/conversations/{conv_id}/tasks', dependencies=[Depends(verify_key)])",
"async def create_task(conv_id: str, body: CreateTask, tenant_id: str):",
"    return supabase.table('tasks').insert({'tenant_id': tenant_id, 'conversation_id': conv_id, 'title': body.title, 'assigned_to': body.assigned_to, 'due_at': body.due_at}).execute().data[0]",
"",
"@app.put('/tasks/{task_id}/done', dependencies=[Depends(verify_key)])",
"async def complete_task(task_id: str):",
"    return supabase.table('tasks').update({'done': True}).eq('id', task_id).execute().data[0]",
]

with open("main.py", "w") as f:
    f.write("\n".join(lines))
print("main.py criado! linhas:", len(lines))
SCRIPT
